# Generated by Django 6.0.2 on 2026-03-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('documents', '0002_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='document',
        ),
        migrations.AddField(
            model_name='agent',
            name='document',
            field=models.ManyToManyField(blank=True, related_name='agents', to='documents.document'),
        ),
    ]
