# Generated by Django 6.0.2 on 2026-03-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_agent_document_agent_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='document',
            new_name='documents',
        ),
    ]
