# Generated by Django 6.0.2 on 2026-03-03 10:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=users.models.default_expiry),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Member')], default=2, null=True, verbose_name='role'),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('tenant', 'email')},
        ),
    ]
